version: '3'

services:
  
  web-application:
    build: "./web-application"
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - "./web-application/src:/web-application/src"
    depends_on:
      - "db"
  db:
    build: "./db"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=abc5555
      - MYSQL_DATABASE=webAppDb

  redis:
    build: './redis-db'
    expose:
      - 6379

  postgres:
    build: './postgresql-db'
    environment: 
      - POSTGRES_USER=webAppPostDb
      - POSTGRES_PASSWORD=5555
      - POSTGRES_DB=dbname
    expose: 
      - 5432

      